name: Deploy Github Pages

on:
  workflow_run:
    workflows: ["Fetch data", "Fetch Luogu data", "Fetch AtCoder data"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Timezone
        run: sudo timedatectl set-timezone "Asia/Shanghai"
      - uses: actions/checkout@v2
      - name: Setup CPany
        uses: cpanyjs/setup-cpany@v0
      - name: Build
        run: cpany build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
