name: Deploy Github Pages

on:
  push:
    branches:
      - main
    paths:
      - package.json
      - nowcoder
  workflow_run:
    workflows: ["Upgrade CPany", "Fetch data", "Fetch Luogu data", "Fetch AtCoder data"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Timezone
        run: sudo timedatectl set-timezone "Asia/Shanghai"
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
        with:
          fetch-depth: 60
      - name: Setup CPany
        uses: cpanyjs/setup-cpany@v0
      - name: Build
        run: cpany build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
